In [1]:
import numpy as np
import pandas as pd

In [10]:
np.set_printoptions(suppress=True,linewidth=100,precision=2)

In [15]:
load_data = np.genfromtxt("loan-data.csv",
                          delimiter=';',
                          encoding=('ISO-8859-1'),
                         skip_header=1,
                         autostrip= True)

In [16]:
load_data

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

In [13]:
load_data.shape

(10001, 14)

In [21]:
#np.savetxt('Loan.csv',load_data,
#          fmt='%s',
#          delimiter=',')

## Checking for Incomplete Data

In [31]:
np.isnan(load_data).sum()

88005

In [32]:
## create a filler for all the missing entries of the dataset

temporary_fill = np.nanmax(load_data) +1

## create also temporary mean Which Hold the means for every column

temporary_mean = np.nanmean(load_data,axis=0)


<ipython-input-32-4e529a07503b>:7: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(load_data,axis=0)


In [35]:
temporary_mean

## This show the mean of each column, and the column with mean "nan" contians no numbers

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

#### From the abave result, we can say that there 8 columns which contain only string, it is shown by NAN 

#### This show the mean of each column, and the column with mean "nan" contians no numbers

## we should split our dataset into two, string column and numuric colum


In [36]:
## let's create a variable called temporary_stats

temporary_stats = np.array([np.nanmin(load_data,axis=0),
                           temporary_mean,
                           np.nanmax(load_data,axis=0)])

<ipython-input-36-4b498c669e17>:3: RuntimeWarning: All-NaN slice encountered
  temporary_stats = np.array([np.nanmin(load_data,axis=0),
<ipython-input-36-4b498c669e17>:5: RuntimeWarning: All-NaN slice encountered
  np.nanmax(load_data,axis=0)])


In [37]:
temporary_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

#### The result above consist of 2D array which contains three 1D arrays and the midle one is temporary_mean

#### the order is maintain, __min__->, __mean__->, __max__

In [52]:
## create variable called columns_strings

columns_strings = np.argwhere(np.isnan(temporary_mean))
columns_strings

#### column     mean         np.isnan()

## contain ==>   =            =

## only text     nan          True

array([[ 1],
       [ 3],
       [ 5],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

## __squeeze()__ help to get the result into one  dimension (1D)

In [53]:
columns_strings1 = np.argwhere(np.isnan(temporary_mean)).squeeze()

columns_strings1

array([ 1,  3,  5,  8,  9, 10, 11, 12])

In [54]:
columns_numeric = np.argwhere(np.isnan(temporary_mean) == False).squeeze()
columns_numeric

array([ 0,  2,  4,  6,  7, 13])

### Great job

#### using : usecols = columns_strings1
#### using : usecols = columns_numeric
#### We can import our dataset as we want it....>>>>>>>>>

## Let's import again our same dataset but into two diffrents __arrays__

In [104]:
load_data_strings = np.genfromtxt("loan-data.csv",
                         delimiter=';',
                         encoding=('ISO-8859-1'),
                         skip_header=1,
                         autostrip= True,
                         usecols=columns_strings1,
                         dtype= np.str_)
load_data_strings

### This gives only string data

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [57]:
load_data_numeric = np.genfromtxt("loan-data.csv",
                         delimiter=';',
                         encoding=('ISO-8859-1'),
                         skip_header=1,
                         autostrip= True,
                         usecols=columns_numeric,
                         filling_values=temporary_fill)
load_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [62]:
load_data_numeric.shape

(10000, 6)

In [63]:
load_data_strings.shape

(10000, 8)

### Well done we have string two datasets: __String_dataset__ and __Numeric_dataset__

## The Names of the Column

In [66]:
header_full = np.genfromtxt("loan-data.csv",
                         delimiter=';',
                         encoding=('ISO-8859-1'),
                         skip_footer=load_data.shape[0],
                         autostrip= True,
                         dtype= np.str_)
header_full
## skip_footer=load_data.shape[0], This will ignore all the rows of the dataset

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

### let's create two different headers

In [67]:
header_strings,header_numeric = header_full[columns_strings1],header_full[columns_numeric]

In [68]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [69]:
header_strings.shape

(8,)

In [70]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [85]:
header_numeric.shape

(6,)

## Creating a Checkpoints:
#### This will help to save the clean data permanently

In [86]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data= checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return checkpoint_variable

In [106]:
checkpoint_test = checkpoint("checkpoint-test",header_strings,load_data_strings)

In [107]:
checkpoint_test['header']

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [108]:
checkpoint_test['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [92]:
np.array_equal(checkpoint_test['data'],load_data_strings)

## checking the both arrays

True

In [93]:
ls


Loan.csv             Pratical1.ipynb      loan-data.csv
Loan_y.csv           checkpoint-test.npz


In [94]:
checkpoint_test_no = checkpoint("checkpoint-test_no",header_numeric,load_data_numeric)

In [100]:
checkpoint_test_no['data']

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [105]:
load_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')