In [28]:
import numpy as np
import pandas as pd

In [24]:
array_a = np.array([[1,2,3],[4,5,6]])

In [35]:
array_a[0][0]

1

In [38]:
array_a[0,0]

1

In [30]:
print(array_a)

[[1 2 3]
 [4 5 6]]


## columns wise

In [55]:
array_a[0:2,1:2]
## column, like a matrix.

array([[2],
       [5]])

In [56]:
array_a[1:2,1:2]
##  column, like a matrix.

array([[5]])

### Altering ndarray

In [57]:
array_b = np.array([[1,2,3],[4,5,6]])

In [58]:
print(array_b)

[[1 2 3]
 [4 5 6]]


In [60]:
array_b[0,2] =10

In [61]:
print(array_b)

[[ 1  2 10]
 [ 4  5  6]]


In [62]:
array_b[1,1]

5

In [63]:
array_b[1,1] = 100

In [64]:
print(array_b)

[[  1   2  10]
 [  4 100   6]]


In [65]:
### Another method

In [66]:
array_b

array([[  1,   2,  10],
       [  4, 100,   6]])

In [67]:
array_b[:] = 10
array_b


array([[10, 10, 10],
       [10, 10, 10]])

In [72]:
array_b[:,0] = 11

## affect only first column

In [73]:
array_b

array([[11,  1,  1],
       [11,  1,  1]])

In [74]:
array_b[0] = 20
## this affect only the first rows the matrix

In [75]:
array_b

array([[20, 20, 20],
       [11,  1,  1]])

In [76]:
print(array_b)

## consider numpy.ndarray as a matrix

[[20 20 20]
 [11  1  1]]


In [77]:
df = array_b

In [78]:
df

array([[20, 20, 20],
       [11,  1,  1]])

In [80]:
df + 1

array([[21, 21, 21],
       [12,  2,  2]])

In [81]:
x = np.array(['hello','yes','no'])

In [82]:
x

array(['hello', 'yes', 'no'], dtype='<U5')

In [83]:
print(x)

['hello' 'yes' 'no']


## Universal Function ?

#### broadcasting 

In [84]:
x_array = np.array([1,2,3])
x_array

array([1, 2, 3])

In [85]:
y_array= np.array([[1],[2]])
y_array

array([[1],
       [2]])

In [88]:
matrix_c = np.array([[1,2,3],[4,5,6]])
matrix_c

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
np.add(x_array,matrix_c)

array([[2, 4, 6],
       [5, 7, 9]])

#### Type_casting

In [92]:
array_d = np.add(x_array,matrix_c, dtype = np.float16)

In [93]:
array_d

array([[2., 4., 6.],
       [5., 7., 9.]], dtype=float16)

In [98]:
matrix_c

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
mean_m = np.mean(matrix_c,axis=1)
mean_m


## rows wise mean .....



array([2., 5.])

In [103]:
mean_m = np.mean(matrix_c,axis=0)
mean_m
## columns wise mean ......


array([2.5, 3.5, 4.5])

 #### empty() method

In [8]:
array_empty = np.empty(shape = (3,4))
array_empty

array([[3.10503618e+231, 2.68679706e+154, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

### zeros() method

In [9]:
array_os = np.zeros(shape =(2,3))
array_os

array([[0., 0., 0.],
       [0., 0., 0.]])

In [111]:
print(array_os)

[[0. 0. 0.]
 [0. 0. 0.]]


In [113]:
array_os1 = np.zeros(shape =(2,3),dtype = np.int8)
array_os1

## integer casting

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [116]:
array_os1 + 1

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

### ones() method

In [117]:
array_ones = np.ones(shape =(2,3))
array_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

#### __full()__ and his argument __fill_value__

In [122]:
array_full= np.full(shape =(2,3), fill_value = 1)
array_full

array([[1, 1, 1],
       [1, 1, 1]])

In [123]:
array_full= np.full(shape =(2,3), fill_value = 'Good morning')
array_full

array([['Good morning', 'Good morning', 'Good morning'],
       ['Good morning', 'Good morning', 'Good morning']], dtype='<U12')

### like() method

In [11]:
val = np.array([ [1,2,3,4,3],[0,3,4,5,6],[3,11,10,12,1]])
val

array([[ 1,  2,  3,  4,  3],
       [ 0,  3,  4,  5,  6],
       [ 3, 11, 10, 12,  1]])

In [12]:
arr_empty_like = np.empty_like(val)
arr_empty_like

array([[                  0,                   0, 4607182418800017408,
        4589168020290535424, 4598175219545276416],
       [4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408, 4617385886705778688],
       [4612248968380809216, 4607182418800017408, 4625196817309499392,
        4616189618054758400, 4607182418800017408]])

In [141]:
arr_os_like = np.zeros_like(val)
arr_os_like 

## create zero array with the same shape as the inner array 

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [143]:
arr_full_like = np.full_like(val,fill_value=11)
arr_full_like 

## create zero array with the same shape as the inner array = val

array([[11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11]])

### __range()__ and __arrange()__

In [144]:
range(5)

range(0, 5)

In [145]:
list(range(5))

[0, 1, 2, 3, 4]

In [146]:
### arange

array_rng = np.arange(30)
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

### __Random Generators__

from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg



In [15]:
pwd

'/Users/olivierla412/Home_trained/doc1'

In [ ]:
#### pcg = Permutation Comgruential Generator

In [150]:
array_RG = gen(pcg())
array_RG.normal()

-1.2529600418535287

In [152]:
array_RG = gen(pcg())
array_RG.normal(size =(3,5))

array([[-0.76696525,  0.54403914,  0.97105838, -1.44446583,  1.15120596],
       [-0.23227285,  1.26920225,  0.1858036 , -1.06182854,  0.07887246],
       [ 1.29768143, -0.20706647, -0.62066003,  0.44396598,  0.56181666]])

### to get same values , let use __seed__ argument.

In [158]:
array_RG = gen(pcg(seed = 365))
array_RG.normal(size =(5,5))

array([[-0.13640899,  0.09414431, -0.06300442,  1.05391641, -0.6866818 ],
       [-0.50922173, -0.7999526 ,  0.73041825,  0.08825439, -2.1177576 ],
       [ 0.65526774, -0.48095012, -0.5519114 , -0.58578662, -0.98257896],
       [ 1.12378166, -1.30984316, -0.04703774,  0.955272  ,  0.26071745],
       [-0.20023668, -1.50172484, -1.4929163 ,  0.96535084,  1.18694633]])

In [159]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [16]:
array_RG = gen(pcg(seed = 365))

In [22]:
result = array_RG.integers(10,size=(4,4))

In [23]:
result

array([[4, 4, 7, 4],
       [2, 6, 3, 5],
       [0, 6, 2, 0],
       [5, 7, 7, 8]])

In [169]:
array_RG.integers(low=10,high = 50,size=(4,4))

array([[26, 29, 38, 29],
       [19, 35, 24, 31],
       [12, 35, 18, 11],
       [31, 38, 38, 43]])

In [170]:
array_RG.random(size=(4,4))

array([[0.17159792, 0.72989385, 0.31220331, 0.4966964 ],
       [0.62633289, 0.25432223, 0.27184357, 0.58527261],
       [0.47582808, 0.31213978, 0.86326571, 0.69308801],
       [0.03810334, 0.7685183 , 0.35663042, 0.10106293]])

In [174]:
ac = array_RG.choice([1,2,3,4,5],size=(4,4))

In [175]:
print(ac)

[[4 4 5 1]
 [5 2 5 1]
 [3 2 3 1]
 [5 2 4 3]]


In [ ]:
array_RG

## Generate Arrays from kown Distributions

In [179]:
array_RG1 = gen(pcg(seed = 365))

In [182]:
array_RG1.poisson(size =(4,4))

array([[0, 0, 1, 2],
       [3, 1, 1, 0],
       [1, 0, 4, 1],
       [2, 2, 2, 0]])

In [183]:
array_RG1.poisson(lam = 10,size =(4,4))

array([[ 9, 12, 10,  7],
       [ 8, 12,  7, 11],
       [ 6,  8, 16, 13],
       [12, 15, 10,  6]])

## Test creation


In [187]:
arr_column1 = array_RG1.normal(loc =2, scale = 3,size =(1000))
arr_column2 = array_RG1.normal(loc =7, scale = 2,size =(1000))
arr_column3 = array_RG1.logistic(loc =11, scale = 3,size =(1000))
arr_column4 = array_RG1.exponential(scale =4 ,size =(1000))
arr_column5 = array_RG1.geometric(p =0.7,size =(1000))

In [190]:
random_test_data = np.array([arr_column1,arr_column2,arr_column3,arr_column4,arr_column5]).transpose()

In [191]:
random_test_data

array([[ 0.86818758,  5.90560375,  8.90594793,  1.66654222,  2.        ],
       [-2.54736585,  9.61769608,  8.77548566,  1.25651593,  1.        ],
       [ 2.40854186, 10.23415854, 18.77001679,  3.56155901,  1.        ],
       ...,
       [ 2.697466  ,  8.82473052,  8.2061061 ,  2.40327928,  1.        ],
       [ 0.86384074,  4.77216952,  6.14456232,  1.21517085,  1.        ],
       [ 4.38801446,  6.42749659, 11.19413878,  0.59960985,  1.        ]])

In [192]:
random_test_data.shape

(1000, 5)

In [193]:
np.savetxt('random_text.csv',random_test_data,fmt='%s',delimiter=',')

In [194]:
### to display the saved file

np.genfromtxt('random_text.csv',delimiter=',')

array([[ 0.86818758,  5.90560375,  8.90594793,  1.66654222,  2.        ],
       [-2.54736585,  9.61769608,  8.77548566,  1.25651593,  1.        ],
       [ 2.40854186, 10.23415854, 18.77001679,  3.56155901,  1.        ],
       ...,
       [ 2.697466  ,  8.82473052,  8.2061061 ,  2.40327928,  1.        ],
       [ 0.86384074,  4.77216952,  6.14456232,  1.21517085,  1.        ],
       [ 4.38801446,  6.42749659, 11.19413878,  0.59960985,  1.        ]])

In [7]:
In

['', 'in', 'IN', 'In', "print('hello')", 'Out', 'x = 20', 'In']

In [4]:
print('hello')

hello


In [5]:
Out

{3: ['', 'in', 'IN', 'In', "print('hello')", 'Out']}

In [6]:
x = 20

In [24]:
import time

In [25]:
for i in range(3):
    print(i,end='')
    time.sleep(3)
    

012

012345

## Importing Data with numpy

#### __np.loadtext()__ vs __np.genfromtxt()__ methods

In [29]:
lending_co_data_numeric1 = np.loadtxt('Lending-Company-Numeric-Data.csv',delimiter=',')
lending_co_data_numeric1
### delimiter = ,

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [30]:
data = pd.read_csv('Lending-Company-Numeric-Data.csv')

In [31]:
data.head(4)

2000  40  365  3121  4241  13621
0  2000  40  365  3061  4171  15041
1  1000  40  365  2160  3280  15340
2  2000  40  365  3041  4241  15321
3  2000  50  365  3470  4820  13720

In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1042 entries, 0 to 1041
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   2000    1042 non-null   int64
 1   40      1042 non-null   int64
 2   365     1042 non-null   int64
 3   3121    1042 non-null   int64
 4   4241    1042 non-null   int64
 5   13621   1042 non-null   int64
dtypes: int64(6)
memory usage: 49.0 KB


In [33]:
data.shape

(1042, 6)

In [34]:
lending_co_data_numeric2 = np.genfromtxt('Lending-Company-Numeric-Data.csv',delimiter=',')
lending_co_data_numeric2

### delimiter = ,

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [35]:
## let check if the both array are the same


np.array_equal(lending_co_data_numeric2 ,lending_co_data_numeric1)

True

In [39]:
#lending_co_data_numeric_NAN1 = np.loadtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter=';')
#lending_co_data_numeric_NAN1

### delimiter = ;

## loadtxt() canNOT handle missing values ( NAN )

In [40]:
lending_co_data_numeric_NAN2 = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter=';')
lending_co_data_numeric_NAN2

### delimiter = ;

## genfromtxt() can handle missing values ( NAN )

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

### Partial Cleaning While Importing data

In [41]:
lending_co_data_numeric_NAN = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter=';')
lending_co_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [42]:
lending_co_data_numeric_NAN = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter=';',skip_header=2)
lending_co_data_numeric_NAN

## This will skip the first two line


array([[ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [43]:
lending_co_data_numeric_NAN = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter=';',usecols=(0,1,5))
lending_co_data_numeric_NAN

array([[ 2000.,    40., 13621.],
       [ 2000.,    40., 15041.],
       [ 1000.,    40., 15340.],
       ...,
       [   nan,    40., 16600.],
       [ 1000.,    40., 15600.],
       [ 2000.,    40., 16600.]])

In [44]:
lending_co_data_numeric_NAN = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter=';',usecols=(5,1,0))
lending_co_data_numeric_NAN

array([[13621.,    40.,  2000.],
       [15041.,    40.,  2000.],
       [15340.,    40.,  1000.],
       ...,
       [16600.,    40.,    nan],
       [15600.,    40.,  1000.],
       [16600.,    40.,  2000.]])

In [46]:
lending_co_data_numeric_NAN = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter=';',usecols=(5,0,1),skip_header=2,skip_footer=2)
lending_co_data_numeric_NAN

array([[15340.,  1000.,    40.],
       [15321.,  2000.,    40.],
       [13720.,  2000.,    50.],
       ...,
       [16600.,  2000.,    40.],
       [16600.,  2000.,    40.],
       [16600.,    nan,    40.]])

## use unpack = true 

In [47]:
### How to store each column in the specific variable

# use unpack = true 

var5,var0,var1 = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter=';',usecols=(5,0,1),skip_header=2,skip_footer=2,unpack= True)

In [48]:

print(var5)
print(var0)
print(var1)

[15340. 15321. 13720. ... 16600. 16600. 16600.]
[1000. 2000. 2000. ... 2000. 2000.   nan]
[40. 40. 50. ... 40. 40. 40.]


## String vs Object vs Numbers

In [50]:
lending_co_lt = np.genfromtxt('lending-co-LT.csv',delimiter=',')
print(lending_co_lt)

[[      nan       nan       nan ...       nan       nan       nan]
 [1.000e+00       nan       nan ...       nan       nan 1.660e+04]
 [2.000e+00       nan       nan ...       nan       nan 1.660e+04]
 ...
 [1.041e+03       nan       nan ...       nan       nan 1.660e+04]
 [1.042e+03       nan       nan ...       nan       nan 1.560e+04]
 [1.043e+03       nan       nan ...       nan       nan 1.660e+04]]


In [51]:
## we can import the data as intiger


lending_co_lt1 = np.genfromtxt('lending-co-LT.csv',delimiter=',',dtype = np.int32)
print(lending_co_lt1)

[[   -1    -1    -1 ...    -1    -1    -1]
 [    1    -1    -1 ...    -1    -1 16600]
 [    2    -1    -1 ...    -1    -1 16600]
 ...
 [ 1041    -1    -1 ...    -1    -1 16600]
 [ 1042    -1    -1 ...    -1    -1 15600]
 [ 1043    -1    -1 ...    -1    -1 16600]]


In [55]:
lending_co_lt1[0,0]+ lending_co_lt1[0,1]

-2

In [56]:
lending_co_lt1[0][0] + lending_co_lt1[0][1]

-2

In [58]:
## we can import the data as string


lending_co_lt2 = np.genfromtxt('lending-co-LT.csv',delimiter=',',dtype = np.str_)
print(lending_co_lt2)

[['LoanID' 'StringID' 'Product' ... 'Location' 'Region' 'TotalPrice']
 ['1' 'id_1' 'Product B' ... 'Location 2' 'Region 2' '16600.0']
 ['2' 'id_2' 'Product B' ... 'Location 3' '' '16600.0']
 ...
 ['1041' 'id_1041' 'Product B' ... 'Location 23' 'Region 4' '16600.0']
 ['1042' 'id_1042' 'Product C' ... 'Location 52' 'Region 6' '15600.0']
 ['1043' 'id_1043' 'Product B' ... 'Location 142' 'Region 6' '16600.0']]


## Saving Files with Numpy

#### __np.save()__

In [60]:
lending_co = np.genfromtxt('Lending-Company-Saving.csv',
                           delimiter=',',
                           dtype =np.str_)
print(lending_co)

[['LoanID' 'StringID' 'Product' ... 'Location' 'Region' 'TotalPrice']
 ['1' 'id_1' 'Product B' ... 'Location 2' 'Region 2' '16600.0']
 ['2' 'id_2' 'Product B' ... 'Location 3' '' '16600.0']
 ...
 ['1041' 'id_1041' 'Product B' ... 'Location 23' 'Region 4' '16600.0']
 ['1042' 'id_1042' 'Product C' ... 'Location 52' 'Region 6' '15600.0']
 ['1043' 'id_1043' 'Product B' ... 'Location 142' 'Region 6' '16600.0']]


In [61]:
## saving the file save('new_fileName', data)


np.save('Lending-Compagny-saving',lending_co)

In [63]:
## let load the new created file

lending_data_save = np.load('Lending-Compagny-saving.npy')
print(lending_data_save)

## not need to specify the delimiter when extension is = .npy

[['LoanID' 'StringID' 'Product' ... 'Location' 'Region' 'TotalPrice']
 ['1' 'id_1' 'Product B' ... 'Location 2' 'Region 2' '16600.0']
 ['2' 'id_2' 'Product B' ... 'Location 3' '' '16600.0']
 ...
 ['1041' 'id_1041' 'Product B' ... 'Location 23' 'Region 4' '16600.0']
 ['1042' 'id_1042' 'Product C' ... 'Location 52' 'Region 6' '15600.0']
 ['1043' 'id_1043' 'Product B' ... 'Location 142' 'Region 6' '16600.0']]


In [64]:
## checking if the both array are equal

np.array_equal(lending_data_save,lending_co)

True

## __np.savez()__ method

In [65]:
lending_co1 = np.genfromtxt('Lending-Company-Saving.csv',
                           delimiter=',',
                           dtype =np.str_)

lending_data_save1 = np.load('Lending-Compagny-saving.npy')

In [67]:
np.savez('Lending-Compagny-saving',lending_co1)

## it creates file with extension = .npz

#### savez can more that one input dataset

In [68]:
np.savez('Lending-Compagny-saving2',lending_co1,lending_data_save1 )

## savez can more that one input dataset

In [69]:
lending_data_save2 = np.load('Lending-Compagny-saving2.npz')
print(lending_data_save2)

## .npz doesn't required delimiter 

In [71]:
## to sovle the above proble , we can used ['arr_0']

print(lending_data_save2['arr_0'],lending_data_save2['arr_1'])

[['LoanID' 'StringID' 'Product' ... 'Location' 'Region' 'TotalPrice']
 ['1' 'id_1' 'Product B' ... 'Location 2' 'Region 2' '16600.0']
 ['2' 'id_2' 'Product B' ... 'Location 3' '' '16600.0']
 ...
 ['1041' 'id_1041' 'Product B' ... 'Location 23' 'Region 4' '16600.0']
 ['1042' 'id_1042' 'Product C' ... 'Location 52' 'Region 6' '15600.0']
 ['1043' 'id_1043' 'Product B' ... 'Location 142' 'Region 6' '16600.0']] [['LoanID' 'StringID' 'Product' ... 'Location' 'Region' 'TotalPrice']
 ['1' 'id_1' 'Product B' ... 'Location 2' 'Region 2' '16600.0']
 ['2' 'id_2' 'Product B' ... 'Location 3' '' '16600.0']
 ...
 ['1041' 'id_1041' 'Product B' ... 'Location 23' 'Region 4' '16600.0']
 ['1042' 'id_1042' 'Product C' ... 'Location 52' 'Region 6' '15600.0']
 ['1043' 'id_1043' 'Product B' ... 'Location 142' 'Region 6' '16600.0']]


### we can give alias name to each array while creating the file 


In [72]:
## we can give alias name to each array while creating the file 


np.savez('Lending-Compagny-saving3',company= lending_co1,data_save= lending_data_save1)

## savez can more that one input dataset

In [78]:
lending_data_savez3 = np.load('Lending-Compagny-saving3.npz')

lending_data_savez3.files

## display using (.files) Objects

['company', 'data_save']

In [75]:
print(lending_data_savez3['company'])

[['LoanID' 'StringID' 'Product' ... 'Location' 'Region' 'TotalPrice']
 ['1' 'id_1' 'Product B' ... 'Location 2' 'Region 2' '16600.0']
 ['2' 'id_2' 'Product B' ... 'Location 3' '' '16600.0']
 ...
 ['1041' 'id_1041' 'Product B' ... 'Location 23' 'Region 4' '16600.0']
 ['1042' 'id_1042' 'Product C' ... 'Location 52' 'Region 6' '15600.0']
 ['1043' 'id_1043' 'Product B' ... 'Location 142' 'Region 6' '16600.0']]


In [76]:
print(lending_data_savez3['data_save'])

[['LoanID' 'StringID' 'Product' ... 'Location' 'Region' 'TotalPrice']
 ['1' 'id_1' 'Product B' ... 'Location 2' 'Region 2' '16600.0']
 ['2' 'id_2' 'Product B' ... 'Location 3' '' '16600.0']
 ...
 ['1041' 'id_1041' 'Product B' ... 'Location 23' 'Region 4' '16600.0']
 ['1042' 'id_1042' 'Product C' ... 'Location 52' 'Region 6' '15600.0']
 ['1043' 'id_1043' 'Product B' ... 'Location 142' 'Region 6' '16600.0']]


In [77]:
np.array_equal(lending_data_savez3['data_save'],lending_data_savez3['company'])

True

In [79]:
print(lending_data_savez3.files)

['company', 'data_save']


## __np.savetxt()__ method

#### it can save the file as __.txt__ or __.csv__

### __.txt__

In [80]:
lending_cc = np.genfromtxt('Lending-Company-Saving.csv',
                           delimiter=',',
                           dtype =np.str_)

In [81]:
np.savetxt('Lending-Compagny-saving.txt',lending_cc,
          fmt='%s',
          delimiter=',')

## fmt = '%s' , means format is = string

In [82]:
lending_data_savetxt = np.genfromtxt('Lending-Compagny-saving.txt',
                                     delimiter=',',dtype =str)
print(lending_data_savetxt)

[['LoanID' 'StringID' 'Product' ... 'Location' 'Region' 'TotalPrice']
 ['1' 'id_1' 'Product B' ... 'Location 2' 'Region 2' '16600.0']
 ['2' 'id_2' 'Product B' ... 'Location 3' '' '16600.0']
 ...
 ['1041' 'id_1041' 'Product B' ... 'Location 23' 'Region 4' '16600.0']
 ['1042' 'id_1042' 'Product C' ... 'Location 52' 'Region 6' '15600.0']
 ['1043' 'id_1043' 'Product B' ... 'Location 142' 'Region 6' '16600.0']]


### Advantages .txt
#### you can open it with __vscode__ Editor or __sublimtext__ ,__notepad++__ and other....

### __.csv__

In [83]:
np.savetxt('Lending.csv',lending_cc,
          fmt='%s',
          delimiter=',')

## fmt = '%s' , means format is = string

In [84]:
open_file = np.genfromtxt('Lending.csv',delimiter=',',dtype = str)
print(open_file)

[['LoanID' 'StringID' 'Product' ... 'Location' 'Region' 'TotalPrice']
 ['1' 'id_1' 'Product B' ... 'Location 2' 'Region 2' '16600.0']
 ['2' 'id_2' 'Product B' ... 'Location 3' '' '16600.0']
 ...
 ['1041' 'id_1041' 'Product B' ... 'Location 23' 'Region 4' '16600.0']
 ['1042' 'id_1042' 'Product C' ... 'Location 52' 'Region 6' '15600.0']
 ['1043' 'id_1043' 'Product B' ... 'Location 142' 'Region 6' '16600.0']]


In [85]:
np.array_equal(open_file,lending_data_savetxt)

True

'/Users/olivierla412/Home_trained/doc1'