## Preprocessing data with Numpy

In [1]:
import numpy as np
import pandas as pd 

In [2]:
lending_co_data_numeric = np.loadtxt('Lending-Company-Numeric-Data.csv',delimiter=',')

## we don't got any error message , that mean there no missing value(NAN)

In [3]:
data = pd.read_csv('Lending-Company-Numeric-Data.csv')

In [4]:
data.head(2)

2000  40  365  3121  4241  13621
0  2000  40  365  3061  4171  15041
1  1000  40  365  2160  3280  15340

In [5]:
np.isnan(lending_co_data_numeric)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       ...,
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [6]:
np.isnan(lending_co_data_numeric).sum()

0

In [7]:
lending_co_data_numeric_nan = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter=';')

lending_co_data_numeric_nan


array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [8]:
np.isnan(lending_co_data_numeric_nan).sum()

#this the total missing values

260

## How fill the missing values

In [9]:
## this help to check the mean of each column of tha dataset

temporary_mean = np.nanmean(lending_co_data_numeric_nan,axis=0).round(2)
temporary_mean

array([ 2250.25,    46.11,   365.  ,  3895.99,  5160.75, 16571.44])

In [10]:
temporary_mean[0]

2250.25

In [11]:
## thsi help to choose the filler value grater than the maximum of the set

temporary_fill = np.nanmax(lending_co_data_numeric_nan).round(2) + 1

lending_co_data_numeric_nan = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',
                                            delimiter=';',
                                           filling_values=temporary_fill)

In [12]:
temporary_fill

64002.0

In [13]:
temporary_mean[0]

## For this coulumn the filler temporary_fill = 64002.0 will outlier

## It will be fine the column temporary_mean[0]


2250.25

In [14]:
## let's check the dataset without missing value

np.mean(lending_co_data_numeric_nan[:,0]).round(2)

## [0:0,0:0] = [lower_row : uper_row,lower_col:uper_col]

4263.25

In [15]:
np.mean(lending_co_data_numeric_nan[:,0]).round(2)


4263.25

In [16]:
temporary_mean[0]


2250.25

In [17]:
lending_co_data_numeric_nan[:,0] = np.where(lending_co_data_numeric_nan[:,0] == temporary_fill,
                                            temporary_mean[0],
                                            lending_co_data_numeric_nan[:,0]
                                           )

In [18]:
np.mean(lending_co_data_numeric_nan[:,0]).round(2)

# new mean

2250.25

In [19]:
length = lending_co_data_numeric_nan.shape[1]

In [20]:
for x in range(length):
    lending_co_data_numeric_nan[:,x] = np.where(lending_co_data_numeric_nan[:,x] == temporary_fill,
                                            temporary_mean[x],
                                            lending_co_data_numeric_nan[:,x]
                                           )

In [21]:
lending_co_data_numeric_nan

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2250.25,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]])

In [22]:
np.mean(lending_co_data_numeric_nan[:,0]).round(2)


2250.25

In [23]:
np.savetxt('data_numeric_nan.csv',lending_co_data_numeric_nan,
          fmt='%d',
          delimiter=',')

In [24]:
df =pd.read_csv('data_numeric_nan.csv')

In [37]:
df.head(1)

2000  40  365  3121  4241  13621
0  2000  40  365  3061  4171  15041

In [28]:
ddd = df['40'].mean()
ddd

46.10652591170825

In [ ]:
type(ddd)

In [29]:
df.describe()

2000           40     365          3121          4241  \
count  1042.000000  1042.000000  1042.0   1042.000000   1042.000000   
mean   2250.479846    46.106526   365.0   3896.677543   5161.606526   
std    1330.027034    12.678966     0.0   2466.087289   2710.298776   
min    1000.000000    35.000000   365.0  -2870.000000  -2870.000000   
25%    2000.000000    40.000000   365.0   2905.000000   3851.000000   
50%    2000.000000    40.000000   365.0   3441.000000   4601.000000   
75%    2000.000000    50.000000   365.0   4875.000000   6242.750000   
max    9000.000000   165.000000   365.0  17650.000000  20001.000000   

              13621  
count   1042.000000  
mean   16574.257198  
std     5911.707292  
min     -350.000000  
25%    14628.250000  
50%    16571.000000  
75%    19225.000000  
max    64001.000000

In [36]:
np.savetxt('data_no.csv',lending_co_data_numeric_nan,
          fmt='%d',
          delimiter=',')

## Reshaping Array

In [41]:
lending_co_data_numerica = np.loadtxt('Lending-company-Numeric.csv',delimiter=',')

In [42]:
lending_co_data_numerica

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [45]:
lending_co_data_numerica.shape

(1043, 6)

In [46]:
np.reshape(lending_co_data_numerica,(6,1043))

array([[ 2000.,    40.,   365., ...,   365.,  1581.,  3041.],
       [12277.,  2000.,    40., ...,    50.,   365.,  5350.],
       [ 6850., 15150.,  1000., ...,  2000.,    40.,   365.],
       [ 3101.,  4351., 16600., ..., 16600.,  2000.,    40.],
       [  365.,  3441.,  4661., ...,  8450., 22250.,  2000.],
       [   40.,   365.,  3701., ...,  4601.,  4601., 16600.]])

In [47]:
## to get back to the current shape

np.transpose(lending_co_data_numerica)

array([[ 2000.,  2000.,  1000., ...,  2000.,  1000.,  2000.],
       [   40.,    40.,    40., ...,    40.,    40.,    40.],
       [  365.,   365.,   365., ...,   365.,   365.,   365.],
       [ 3121.,  3061.,  2160., ...,  4201.,  2080.,  4601.],
       [ 4241.,  4171.,  3280., ...,  5001.,  3320.,  4601.],
       [13621., 15041., 15340., ..., 16600., 15600., 16600.]])

In [50]:
## second way

lending_co_data_numerica.reshape(6,1043)

array([[ 2000.,    40.,   365., ...,   365.,  1581.,  3041.],
       [12277.,  2000.,    40., ...,    50.,   365.,  5350.],
       [ 6850., 15150.,  1000., ...,  2000.,    40.,   365.],
       [ 3101.,  4351., 16600., ..., 16600.,  2000.,    40.],
       [  365.,  3441.,  4661., ...,  8450., 22250.,  2000.],
       [   40.,   365.,  3701., ...,  4601.,  4601., 16600.]])

## Sorting Data

In [51]:
np.sort(lending_co_data_numerica)

array([[   40.,   365.,  2000.,  3121.,  4241., 13621.],
       [   40.,   365.,  2000.,  3061.,  4171., 15041.],
       [   40.,   365.,  1000.,  2160.,  3280., 15340.],
       ...,
       [   40.,   365.,  2000.,  4201.,  5001., 16600.],
       [   40.,   365.,  1000.,  2080.,  3320., 15600.],
       [   40.,   365.,  2000.,  4601.,  4601., 16600.]])

### let's sort the array in descending order by adding minus (-)

In [52]:
arr1 = np.sort(-lending_co_data_numerica)
arr1

array([[-13621.,  -4241.,  -3121.,  -2000.,   -365.,    -40.],
       [-15041.,  -4171.,  -3061.,  -2000.,   -365.,    -40.],
       [-15340.,  -3280.,  -2160.,  -1000.,   -365.,    -40.],
       ...,
       [-16600.,  -5001.,  -4201.,  -2000.,   -365.,    -40.],
       [-15600.,  -3320.,  -2080.,  -1000.,   -365.,    -40.],
       [-16600.,  -4601.,  -4601.,  -2000.,   -365.,    -40.]])

In [53]:
arr2 = -arr1

In [54]:
arr2

array([[13621.,  4241.,  3121.,  2000.,   365.,    40.],
       [15041.,  4171.,  3061.,  2000.,   365.,    40.],
       [15340.,  3280.,  2160.,  1000.,   365.,    40.],
       ...,
       [16600.,  5001.,  4201.,  2000.,   365.,    40.],
       [15600.,  3320.,  2080.,  1000.,   365.,    40.],
       [16600.,  4601.,  4601.,  2000.,   365.,    40.]])

In [55]:
np.transpose(arr2)

array([[13621., 15041., 15340., ..., 16600., 15600., 16600.],
       [ 4241.,  4171.,  3280., ...,  5001.,  3320.,  4601.],
       [ 3121.,  3061.,  2160., ...,  4201.,  2080.,  4601.],
       [ 2000.,  2000.,  1000., ...,  2000.,  1000.,  2000.],
       [  365.,   365.,   365., ...,   365.,   365.,   365.],
       [   40.,    40.,    40., ...,    40.,    40.,    40.]])

### How to sort a specific colum data ?

In [56]:
lending_co_data_numerica

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [57]:
np.sort(lending_co_data_numerica[:,3])

array([-2870., -2550., -2450., ..., 16751., 17650., 19001.])

In [58]:
lending_co_data_numerica[:,3].sort()

In [59]:
lending_co_data_numerica

array([[ 2000.,    40.,   365., -2870.,  4241., 13621.],
       [ 2000.,    40.,   365., -2550.,  4171., 15041.],
       [ 1000.,    40.,   365., -2450.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365., 16751.,  5001., 16600.],
       [ 1000.,    40.,   365., 17650.,  3320., 15600.],
       [ 2000.,    40.,   365., 19001.,  4601., 16600.]])

## sorting only the column 2

In [67]:
lending_co_data_numerica[:,1].sort()

In [68]:
lending_co_data_numerica

array([[ 2000.,    35.,   365., -2870.,  4241., 13621.],
       [ 2000.,    35.,   365., -2550.,  4171., 15041.],
       [ 1000.,    35.,   365., -2450.,  3280., 15340.],
       ...,
       [ 2000.,   125.,   365., 16751.,  5001., 16600.],
       [ 1000.,   165.,   365., 17650.,  3320., 15600.],
       [ 2000.,   165.,   365., 19001.,  4601., 16600.]])

In [69]:
## checking the minimum of the 2nd cloumn

lending_co_data_numerica[:,1].min()

35.0

In [70]:
np.min(lending_co_data_numerica[:,1])

35.0

In [73]:
## sorting only the first row

lending_co_data_numerica[0:1,].sort()

In [74]:
lending_co_data_numerica

array([[-2870.,    35.,   365.,  2000.,  4241., 13621.],
       [-2550.,    35.,   365.,  2000.,  4171., 15041.],
       [-2450.,    35.,   365.,  1000.,  3280., 15340.],
       ...,
       [  125.,   365.,  2000.,  5001., 16600., 16751.],
       [  165.,   365.,  1000.,  3320., 15600., 17650.],
       [  165.,   365.,  2000.,  4601., 16600., 19001.]])

In [77]:
lending_co_data_numerica[0:1,]

## this will selected only the first row of the dataset

array([[-2870.,    35.,   365.,  2000.,  4241., 13621.]])

In [78]:
### To sort the entire dataset and column wise set axis =0

lending_co_data_numerica.sort(axis =0)
lending_co_data_numerica


array([[-2.8700e+03, -3.5000e+02,  4.0000e+01,  3.6500e+02,  1.0000e+03,
         1.1600e+03],
       [-2.8700e+03,  3.5000e+01,  1.0000e+02,  3.6500e+02,  1.0000e+03,
         1.5000e+03],
       [-2.5500e+03,  3.5000e+01,  1.5000e+02,  3.6500e+02,  1.0000e+03,
         2.2000e+03],
       ...,
       [ 1.2500e+02,  3.6500e+02,  7.2510e+03,  9.2010e+03,  1.8751e+04,
         5.4625e+04],
       [ 1.6500e+02,  3.6500e+02,  9.0000e+03,  1.2126e+04,  2.0001e+04,
         5.4625e+04],
       [ 1.6500e+02,  3.6500e+02,  9.0000e+03,  1.3900e+04,  2.2001e+04,
         6.4001e+04]])

## This help to change the exponential to fixe number

In [79]:
np.set_printoptions(suppress= True)

In [80]:
lending_co_data_numerica

array([[-2870.,  -350.,    40.,   365.,  1000.,  1160.],
       [-2870.,    35.,   100.,   365.,  1000.,  1500.],
       [-2550.,    35.,   150.,   365.,  1000.,  2200.],
       ...,
       [  125.,   365.,  7251.,  9201., 18751., 54625.],
       [  165.,   365.,  9000., 12126., 20001., 54625.],
       [  165.,   365.,  9000., 13900., 22001., 64001.]])

## Argument Functions

In [87]:
lending_co_data_numericb = np.loadtxt('Lending-company-Numeric.csv',delimiter=',')
lending_co_data_numericb

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

### __np.argsort()__ method for sorting array

In [88]:
## example
np.argsort(lending_co_data_numericb)

array([[1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5],
       ...,
       [1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5]])

In [89]:
lending_co_data_numericb.sort()

In [90]:
lending_co_data_numericb

array([[   40.,   365.,  2000.,  3121.,  4241., 13621.],
       [   40.,   365.,  2000.,  3061.,  4171., 15041.],
       [   40.,   365.,  1000.,  2160.,  3280., 15340.],
       ...,
       [   40.,   365.,  2000.,  4201.,  5001., 16600.],
       [   40.,   365.,  1000.,  2080.,  3320., 15600.],
       [   40.,   365.,  2000.,  4601.,  4601., 16600.]])

In [91]:
np.argsort(lending_co_data_numericb,axis = 0)

array([[  32,   32,  482,  482,  482,  493],
       [ 166,  166,  218,  493,  493,  482],
       [  85,   85,  227,  448,  635,  166],
       ...,
       [ 442,  367,  202,  568, 1019,  568],
       [ 408,  354,  288,  718, 1033,  534],
       [  27, 1042,  234,  912,  912,   27]])

In [94]:
lending_co_data_numericb[:,0]

array([40., 40., 40., ..., 40., 40., 40.])

### Let's sort the dataset base on the first column

In [95]:
lending_co_data_numericb = lending_co_data_numericb[np.argsort(lending_co_data_numericb[:,0])]

In [96]:
lending_co_data_numericb

array([[-2870., -2870.,    50.,   365.,  1000.,  1160.],
       [-2550., -2100.,    50.,   365.,  1000.,  1100.],
       [-2450., -2000.,    50.,   365.,  1000.,  1500.],
       ...,
       [  125.,   365.,  9000., 12701., 16331., 52681.],
       [  165.,   365.,  9000., 14460., 18050., 37903.],
       [  165.,   365.,  9000., 14501., 16846., 64001.]])

## __np.argwhere()__ , How it works? let's analyse it.

#### It's helpful on finding the location of the specific item, when you set condition to False

In [97]:
lending_co_data_numericd = np.loadtxt('Lending-company-Numeric.csv',delimiter=',')
lending_co_data_numericd

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [98]:
np.argwhere(lending_co_data_numericd)

array([[   0,    0],
       [   0,    1],
       [   0,    2],
       ...,
       [1042,    3],
       [1042,    4],
       [1042,    5]])

In [99]:
# [row_index, column_index]

In [ ]:
### Let's set set condition to false and check where 0 value is located in the 
### dataset and the coordinates

In [100]:
np.argwhere(lending_co_data_numericd == False)

array([[116,   4],
       [430,   3]])

### [116, 4] , means at row 116 and column 4 there 0 and at [430, 3]
### there only two zero in dataset.

In [103]:
lending_co_data_numericd[116]



array([ 1000.,    50.,   365., -1450.,     0., 13850.])

In [104]:
lending_co_data_numericd[116,4]


0.0

In [105]:
lending_co_data_numericd[430,3]


0.0

### How to use __np.argwhere__ to fixe NAN values ?

In [109]:
lending_co_data_numeric_NAN = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter=';')
lending_co_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [110]:
np.isnan(lending_co_data_numeric_NAN).sum()

## some of missing values

260

# This gives the coordinates for all missing values of the array

In [113]:
np.argwhere(np.isnan(lending_co_data_numeric_NAN))

## This gives the coordinates for all missing values of the array

array([[  11,    3],
       [  15,    3],
       [  27,    3],
       [  58,    3],
       [  60,    4],
       [  85,    4],
       [ 117,    5],
       [ 152,    1],
       [ 152,    2],
       [ 152,    4],
       [ 172,    1],
       [ 175,    1],
       [ 175,    2],
       [ 176,    3],
       [ 177,    4],
       [ 178,    5],
       [ 211,    3],
       [ 229,    0],
       [ 230,    1],
       [ 237,    1],
       [ 247,    3],
       [ 251,    5],
       [ 252,    4],
       [ 258,    1],
       [ 260,    3],
       [ 262,    4],
       [ 271,    5],
       [ 272,    4],
       [ 284,    2],
       [ 284,    3],
       [ 297,    1],
       [ 297,    2],
       [ 300,    3],
       [ 315,    3],
       [ 315,    5],
       [ 327,    4],
       [ 336,    4],
       [ 343,    0],
       [ 344,    2],
       [ 346,    2],
       [ 363,    3],
       [ 375,    3],
       [ 377,    2],
       [ 398,    5],
       [ 416,    4],
       [ 428,    0],
       [ 432,    1],
       [ 433,

In [117]:
lending_co_data_numeric_NAN[1040,0]

40.0

In [118]:
lending_co_data_numeric_NAN[1040]

array([   nan,    40.,   365.,  4201.,  5001., 16600.])

### We will use the structure of a very simple __for loop__

In [120]:
for array_index in np.argwhere(np.isnan(lending_co_data_numeric_NAN)):
    #print(lending_co_data_numeric_NAN[array_index[0],array_index[1]])
    lending_co_data_numeric_NAN[array_index[0],array_index[1]] = 0

In [121]:
## let's check again the dataset after filled out the NAN values with 0

np.isnan(lending_co_data_numeric_NAN).sum()


0

### __np.savetxt__

In [127]:
## let's save the clean data using np.savetxt

np.savetxt('lending_co_data_numeric_NAN_fill_By_Zero1.csv',lending_co_data_numeric_NAN,
          fmt='%s',
          delimiter=',')


In [122]:
lending_co_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [    0.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [128]:
fill_by_zero = pd.read_csv('lending_co_data_numeric_NAN_fill_By_Zero1.csv')
fill_by_zero.head(3)

2000.0  40.0  365.0  3121.0  4241.0  13621.0
0  2000.0  40.0  365.0  3061.0  4171.0  15041.0
1  1000.0  40.0  365.0  2160.0  3280.0  15340.0
2  2000.0  40.0  365.0  3041.0  4241.0  15321.0