## Preprocessing data with Numpy

In [1]:
import numpy as np
import pandas as pd 

In [2]:
lending_co_data_numeric = np.loadtxt('Lending-Company-Numeric-Data.csv',delimiter=',')

## we don't got any error message , that mean there no missing value(NAN)

In [3]:
data = pd.read_csv('Lending-Company-Numeric-Data.csv')

In [4]:
data.head(2)

2000  40  365  3121  4241  13621
0  2000  40  365  3061  4171  15041
1  1000  40  365  2160  3280  15340

In [5]:
np.isnan(lending_co_data_numeric)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       ...,
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [6]:
np.isnan(lending_co_data_numeric).sum()

0

In [7]:
lending_co_data_numeric_nan = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter=';')

lending_co_data_numeric_nan


array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [8]:
np.isnan(lending_co_data_numeric_nan).sum()

#this the total missing values

260

## How fill the missing values

In [9]:
## this help to check the mean of each column of tha dataset

temporary_mean = np.nanmean(lending_co_data_numeric_nan,axis=0).round(2)
temporary_mean

array([ 2250.25,    46.11,   365.  ,  3895.99,  5160.75, 16571.44])

In [10]:
temporary_mean[0]

2250.25

In [11]:
## thsi help to choose the filler value grater than the maximum of the set

temporary_fill = np.nanmax(lending_co_data_numeric_nan).round(2) + 1

lending_co_data_numeric_nan = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',
                                            delimiter=';',
                                           filling_values=temporary_fill)

In [12]:
temporary_fill

64002.0

In [13]:
temporary_mean[0]

## For this coulumn the filler temporary_fill = 64002.0 will outlier

## It will be fine the column temporary_mean[0]


2250.25

In [14]:
## let's check the dataset without missing value

np.mean(lending_co_data_numeric_nan[:,0]).round(2)

## [0:0,0:0] = [lower_row : uper_row,lower_col:uper_col]

4263.25

In [15]:
np.mean(lending_co_data_numeric_nan[:,0]).round(2)


4263.25

In [16]:
temporary_mean[0]


2250.25

In [17]:
lending_co_data_numeric_nan[:,0] = np.where(lending_co_data_numeric_nan[:,0] == temporary_fill,
                                            temporary_mean[0],
                                            lending_co_data_numeric_nan[:,0]
                                           )

In [18]:
np.mean(lending_co_data_numeric_nan[:,0]).round(2)

# new mean

2250.25

In [293]:
length = lending_co_data_numeric_nan.shape[1]

In [20]:
for x in range(length):
    lending_co_data_numeric_nan[:,x] = np.where(lending_co_data_numeric_nan[:,x] == temporary_fill,
                                            temporary_mean[x],
                                            lending_co_data_numeric_nan[:,x]
                                           )

In [21]:
lending_co_data_numeric_nan

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2250.25,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]])

In [22]:
np.mean(lending_co_data_numeric_nan[:,0]).round(2)


2250.25

In [23]:
np.savetxt('data_numeric_nan.csv',lending_co_data_numeric_nan,
          fmt='%d',
          delimiter=',')

In [24]:
df =pd.read_csv('data_numeric_nan.csv')

In [37]:
df.head(1)

2000  40  365  3121  4241  13621
0  2000  40  365  3061  4171  15041

In [28]:
ddd = df['40'].mean()
ddd

46.10652591170825

In [ ]:
type(ddd)

In [29]:
df.describe()

2000           40     365          3121          4241  \
count  1042.000000  1042.000000  1042.0   1042.000000   1042.000000   
mean   2250.479846    46.106526   365.0   3896.677543   5161.606526   
std    1330.027034    12.678966     0.0   2466.087289   2710.298776   
min    1000.000000    35.000000   365.0  -2870.000000  -2870.000000   
25%    2000.000000    40.000000   365.0   2905.000000   3851.000000   
50%    2000.000000    40.000000   365.0   3441.000000   4601.000000   
75%    2000.000000    50.000000   365.0   4875.000000   6242.750000   
max    9000.000000   165.000000   365.0  17650.000000  20001.000000   

              13621  
count   1042.000000  
mean   16574.257198  
std     5911.707292  
min     -350.000000  
25%    14628.250000  
50%    16571.000000  
75%    19225.000000  
max    64001.000000

In [36]:
np.savetxt('data_no.csv',lending_co_data_numeric_nan,
          fmt='%d',
          delimiter=',')

## Reshaping Array

In [41]:
lending_co_data_numerica = np.loadtxt('Lending-company-Numeric.csv',delimiter=',')

In [42]:
lending_co_data_numerica

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [45]:
lending_co_data_numerica.shape

(1043, 6)

In [46]:
np.reshape(lending_co_data_numerica,(6,1043))

array([[ 2000.,    40.,   365., ...,   365.,  1581.,  3041.],
       [12277.,  2000.,    40., ...,    50.,   365.,  5350.],
       [ 6850., 15150.,  1000., ...,  2000.,    40.,   365.],
       [ 3101.,  4351., 16600., ..., 16600.,  2000.,    40.],
       [  365.,  3441.,  4661., ...,  8450., 22250.,  2000.],
       [   40.,   365.,  3701., ...,  4601.,  4601., 16600.]])

In [47]:
## to get back to the current shape

np.transpose(lending_co_data_numerica)

array([[ 2000.,  2000.,  1000., ...,  2000.,  1000.,  2000.],
       [   40.,    40.,    40., ...,    40.,    40.,    40.],
       [  365.,   365.,   365., ...,   365.,   365.,   365.],
       [ 3121.,  3061.,  2160., ...,  4201.,  2080.,  4601.],
       [ 4241.,  4171.,  3280., ...,  5001.,  3320.,  4601.],
       [13621., 15041., 15340., ..., 16600., 15600., 16600.]])

In [50]:
## second way

lending_co_data_numerica.reshape(6,1043)

array([[ 2000.,    40.,   365., ...,   365.,  1581.,  3041.],
       [12277.,  2000.,    40., ...,    50.,   365.,  5350.],
       [ 6850., 15150.,  1000., ...,  2000.,    40.,   365.],
       [ 3101.,  4351., 16600., ..., 16600.,  2000.,    40.],
       [  365.,  3441.,  4661., ...,  8450., 22250.,  2000.],
       [   40.,   365.,  3701., ...,  4601.,  4601., 16600.]])

## Sorting Data

In [51]:
np.sort(lending_co_data_numerica)

array([[   40.,   365.,  2000.,  3121.,  4241., 13621.],
       [   40.,   365.,  2000.,  3061.,  4171., 15041.],
       [   40.,   365.,  1000.,  2160.,  3280., 15340.],
       ...,
       [   40.,   365.,  2000.,  4201.,  5001., 16600.],
       [   40.,   365.,  1000.,  2080.,  3320., 15600.],
       [   40.,   365.,  2000.,  4601.,  4601., 16600.]])

### let's sort the array in descending order by adding minus (-)

In [52]:
arr1 = np.sort(-lending_co_data_numerica)
arr1

array([[-13621.,  -4241.,  -3121.,  -2000.,   -365.,    -40.],
       [-15041.,  -4171.,  -3061.,  -2000.,   -365.,    -40.],
       [-15340.,  -3280.,  -2160.,  -1000.,   -365.,    -40.],
       ...,
       [-16600.,  -5001.,  -4201.,  -2000.,   -365.,    -40.],
       [-15600.,  -3320.,  -2080.,  -1000.,   -365.,    -40.],
       [-16600.,  -4601.,  -4601.,  -2000.,   -365.,    -40.]])

In [53]:
arr2 = -arr1

In [54]:
arr2

array([[13621.,  4241.,  3121.,  2000.,   365.,    40.],
       [15041.,  4171.,  3061.,  2000.,   365.,    40.],
       [15340.,  3280.,  2160.,  1000.,   365.,    40.],
       ...,
       [16600.,  5001.,  4201.,  2000.,   365.,    40.],
       [15600.,  3320.,  2080.,  1000.,   365.,    40.],
       [16600.,  4601.,  4601.,  2000.,   365.,    40.]])

In [55]:
np.transpose(arr2)

array([[13621., 15041., 15340., ..., 16600., 15600., 16600.],
       [ 4241.,  4171.,  3280., ...,  5001.,  3320.,  4601.],
       [ 3121.,  3061.,  2160., ...,  4201.,  2080.,  4601.],
       [ 2000.,  2000.,  1000., ...,  2000.,  1000.,  2000.],
       [  365.,   365.,   365., ...,   365.,   365.,   365.],
       [   40.,    40.,    40., ...,    40.,    40.,    40.]])

### How to sort a specific colum data ?

In [56]:
lending_co_data_numerica

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [57]:
np.sort(lending_co_data_numerica[:,3])

array([-2870., -2550., -2450., ..., 16751., 17650., 19001.])

In [58]:
lending_co_data_numerica[:,3].sort()

In [59]:
lending_co_data_numerica

array([[ 2000.,    40.,   365., -2870.,  4241., 13621.],
       [ 2000.,    40.,   365., -2550.,  4171., 15041.],
       [ 1000.,    40.,   365., -2450.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365., 16751.,  5001., 16600.],
       [ 1000.,    40.,   365., 17650.,  3320., 15600.],
       [ 2000.,    40.,   365., 19001.,  4601., 16600.]])

## sorting only the column 2

In [67]:
lending_co_data_numerica[:,1].sort()

In [68]:
lending_co_data_numerica

array([[ 2000.,    35.,   365., -2870.,  4241., 13621.],
       [ 2000.,    35.,   365., -2550.,  4171., 15041.],
       [ 1000.,    35.,   365., -2450.,  3280., 15340.],
       ...,
       [ 2000.,   125.,   365., 16751.,  5001., 16600.],
       [ 1000.,   165.,   365., 17650.,  3320., 15600.],
       [ 2000.,   165.,   365., 19001.,  4601., 16600.]])

In [69]:
## checking the minimum of the 2nd cloumn

lending_co_data_numerica[:,1].min()

35.0

In [70]:
np.min(lending_co_data_numerica[:,1])

35.0

In [73]:
## sorting only the first row

lending_co_data_numerica[0:1,].sort()

In [74]:
lending_co_data_numerica

array([[-2870.,    35.,   365.,  2000.,  4241., 13621.],
       [-2550.,    35.,   365.,  2000.,  4171., 15041.],
       [-2450.,    35.,   365.,  1000.,  3280., 15340.],
       ...,
       [  125.,   365.,  2000.,  5001., 16600., 16751.],
       [  165.,   365.,  1000.,  3320., 15600., 17650.],
       [  165.,   365.,  2000.,  4601., 16600., 19001.]])

In [77]:
lending_co_data_numerica[0:1,]

## this will selected only the first row of the dataset

array([[-2870.,    35.,   365.,  2000.,  4241., 13621.]])

In [78]:
### To sort the entire dataset and column wise set axis =0

lending_co_data_numerica.sort(axis =0)
lending_co_data_numerica


array([[-2.8700e+03, -3.5000e+02,  4.0000e+01,  3.6500e+02,  1.0000e+03,
         1.1600e+03],
       [-2.8700e+03,  3.5000e+01,  1.0000e+02,  3.6500e+02,  1.0000e+03,
         1.5000e+03],
       [-2.5500e+03,  3.5000e+01,  1.5000e+02,  3.6500e+02,  1.0000e+03,
         2.2000e+03],
       ...,
       [ 1.2500e+02,  3.6500e+02,  7.2510e+03,  9.2010e+03,  1.8751e+04,
         5.4625e+04],
       [ 1.6500e+02,  3.6500e+02,  9.0000e+03,  1.2126e+04,  2.0001e+04,
         5.4625e+04],
       [ 1.6500e+02,  3.6500e+02,  9.0000e+03,  1.3900e+04,  2.2001e+04,
         6.4001e+04]])

## This help to change the exponential to fixe number

In [79]:
np.set_printoptions(suppress= True)

In [80]:
lending_co_data_numerica

array([[-2870.,  -350.,    40.,   365.,  1000.,  1160.],
       [-2870.,    35.,   100.,   365.,  1000.,  1500.],
       [-2550.,    35.,   150.,   365.,  1000.,  2200.],
       ...,
       [  125.,   365.,  7251.,  9201., 18751., 54625.],
       [  165.,   365.,  9000., 12126., 20001., 54625.],
       [  165.,   365.,  9000., 13900., 22001., 64001.]])

## Argument Functions

In [87]:
lending_co_data_numericb = np.loadtxt('Lending-company-Numeric.csv',delimiter=',')
lending_co_data_numericb

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

### __np.argsort()__ method for sorting array

In [88]:
## example
np.argsort(lending_co_data_numericb)

array([[1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5],
       ...,
       [1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5]])

In [89]:
lending_co_data_numericb.sort()

In [90]:
lending_co_data_numericb

array([[   40.,   365.,  2000.,  3121.,  4241., 13621.],
       [   40.,   365.,  2000.,  3061.,  4171., 15041.],
       [   40.,   365.,  1000.,  2160.,  3280., 15340.],
       ...,
       [   40.,   365.,  2000.,  4201.,  5001., 16600.],
       [   40.,   365.,  1000.,  2080.,  3320., 15600.],
       [   40.,   365.,  2000.,  4601.,  4601., 16600.]])

In [91]:
np.argsort(lending_co_data_numericb,axis = 0)

array([[  32,   32,  482,  482,  482,  493],
       [ 166,  166,  218,  493,  493,  482],
       [  85,   85,  227,  448,  635,  166],
       ...,
       [ 442,  367,  202,  568, 1019,  568],
       [ 408,  354,  288,  718, 1033,  534],
       [  27, 1042,  234,  912,  912,   27]])

In [94]:
lending_co_data_numericb[:,0]

array([40., 40., 40., ..., 40., 40., 40.])

### Let's sort the dataset base on the first column

In [95]:
lending_co_data_numericb = lending_co_data_numericb[np.argsort(lending_co_data_numericb[:,0])]

In [96]:
lending_co_data_numericb

array([[-2870., -2870.,    50.,   365.,  1000.,  1160.],
       [-2550., -2100.,    50.,   365.,  1000.,  1100.],
       [-2450., -2000.,    50.,   365.,  1000.,  1500.],
       ...,
       [  125.,   365.,  9000., 12701., 16331., 52681.],
       [  165.,   365.,  9000., 14460., 18050., 37903.],
       [  165.,   365.,  9000., 14501., 16846., 64001.]])

## __np.argwhere()__ , How it works? let's analyse it.

#### It's helpful on finding the location of the specific item, when you set condition to False

In [97]:
lending_co_data_numericd = np.loadtxt('Lending-company-Numeric.csv',delimiter=',')
lending_co_data_numericd

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [98]:
np.argwhere(lending_co_data_numericd)

array([[   0,    0],
       [   0,    1],
       [   0,    2],
       ...,
       [1042,    3],
       [1042,    4],
       [1042,    5]])

In [99]:
# [row_index, column_index]

In [ ]:
### Let's set set condition to false and check where 0 value is located in the 
### dataset and the coordinates

In [100]:
np.argwhere(lending_co_data_numericd == False)

array([[116,   4],
       [430,   3]])

### [116, 4] , means at row 116 and column 4 there 0 and at [430, 3]
### there only two zero in dataset.

In [103]:
lending_co_data_numericd[116]



array([ 1000.,    50.,   365., -1450.,     0., 13850.])

In [104]:
lending_co_data_numericd[116,4]


0.0

In [105]:
lending_co_data_numericd[430,3]


0.0

### How to use __np.argwhere__ to fixe NAN values ?

In [109]:
lending_co_data_numeric_NAN = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter=';')
lending_co_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [110]:
np.isnan(lending_co_data_numeric_NAN).sum()

## some of missing values

260

# This gives the coordinates for all missing values of the array

In [113]:
np.argwhere(np.isnan(lending_co_data_numeric_NAN))

## This gives the coordinates for all missing values of the array

array([[  11,    3],
       [  15,    3],
       [  27,    3],
       [  58,    3],
       [  60,    4],
       [  85,    4],
       [ 117,    5],
       [ 152,    1],
       [ 152,    2],
       [ 152,    4],
       [ 172,    1],
       [ 175,    1],
       [ 175,    2],
       [ 176,    3],
       [ 177,    4],
       [ 178,    5],
       [ 211,    3],
       [ 229,    0],
       [ 230,    1],
       [ 237,    1],
       [ 247,    3],
       [ 251,    5],
       [ 252,    4],
       [ 258,    1],
       [ 260,    3],
       [ 262,    4],
       [ 271,    5],
       [ 272,    4],
       [ 284,    2],
       [ 284,    3],
       [ 297,    1],
       [ 297,    2],
       [ 300,    3],
       [ 315,    3],
       [ 315,    5],
       [ 327,    4],
       [ 336,    4],
       [ 343,    0],
       [ 344,    2],
       [ 346,    2],
       [ 363,    3],
       [ 375,    3],
       [ 377,    2],
       [ 398,    5],
       [ 416,    4],
       [ 428,    0],
       [ 432,    1],
       [ 433,

In [129]:
lending_co_data_numeric_NAN[1040,0]

0.0

In [118]:
lending_co_data_numeric_NAN[1040]

array([   nan,    40.,   365.,  4201.,  5001., 16600.])

### We will use the structure of a very simple __for loop__

In [120]:
for array_index in np.argwhere(np.isnan(lending_co_data_numeric_NAN)):
    #print(lending_co_data_numeric_NAN[array_index[0],array_index[1]])
    lending_co_data_numeric_NAN[array_index[0],array_index[1]] = 0

In [121]:
## let's check again the dataset after filled out the NAN values with 0

np.isnan(lending_co_data_numeric_NAN).sum()


0

### __np.savetxt__

In [127]:
## let's save the clean data using np.savetxt

np.savetxt('lending_co_data_numeric_NAN_fill_By_Zero1.csv',lending_co_data_numeric_NAN,
          fmt='%s',
          delimiter=',')


In [122]:
lending_co_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [    0.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [128]:
fill_by_zero = pd.read_csv('lending_co_data_numeric_NAN_fill_By_Zero1.csv')
fill_by_zero.head(3)

2000.0  40.0  365.0  3121.0  4241.0  13621.0
0  2000.0  40.0  365.0  3061.0  4171.0  15041.0
1  1000.0  40.0  365.0  2160.0  3280.0  15340.0
2  2000.0  40.0  365.0  3041.0  4241.0  15321.0

## Shuffling Data

In [130]:
## import the dataset and take only the first 8 rows

lending_co_data_numericf = np.loadtxt('Lending-company-Numeric.csv',delimiter=',')[:8]
lending_co_data_numericf

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       [ 2000.,    40.,   365.,  3201.,  4141., 14141.],
       [ 2000.,    50.,   365.,  1851.,  3251., 17701.],
       [ 2000.,    40.,   365.,  3971.,  4131., 15351.]])

## Let's apply shuffling

In [135]:
## this will modify the dataset lending_co_data_numericf

np.random.shuffle(lending_co_data_numericf)
lending_co_data_numericf

array([[ 2000.,    50.,   365.,  1851.,  3251., 17701.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       [ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3971.,  4131., 15351.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    40.,   365.,  3201.,  4141., 14141.]])

In [136]:
from numpy.random import shuffle

In [137]:
## Let's import again the intire dataset

lending_co_data_numericg = np.loadtxt('Lending-company-Numeric.csv',delimiter=',')
lending_co_data_numericg

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

## to shuffle the data = pour mélanger les données.

In [140]:
shuffle(lending_co_data_numericg)
lending_co_data_numericg

array([[ 2000.,    50.,   365., 12001., 12001., 20250.],
       [ 2000.,    50.,   365.,  7251.,  7251., 20250.],
       [ 1000.,    50.,   365.,   200.,   700., 19250.],
       ...,
       [ 2000.,    50.,   365.,  4000.,  6000., 14590.],
       [ 4000.,    50.,   365.,  5450.,  7250., 22250.],
       [ 2000.,    40.,   365.,  2761.,  3961., 12431.]])

## Shuffle Generator

In [143]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg
from numpy.random import shuffle

In [142]:
array_RG = gen(pcg())

In [149]:
array_RG.shuffle(lending_co_data_numericg)
lending_co_data_numericg

array([[ 2000.,    40.,   365.,  3290.,  4330., 14524.],
       [ 2000.,    40.,   365.,  3401.,  7401., 16600.],
       [ 4000.,    50.,   365.,  6300.,  8000., 22250.],
       ...,
       [ 9000.,   125.,   365., 12251., 14251., 25626.],
       [ 2000.,    40.,   365.,  7951.,  7951., 16600.],
       [ 2000.,    50.,   365.,  4250.,  7250., 20250.]])

## __Array Casting__ / __Type Casting__

In [150]:
## Let's import again the intire dataset.
lending_co_data_numerich = np.loadtxt('Lending-company-Numeric.csv',delimiter=',')
lending_co_data_numerich

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

#### Let's change the type of the loaded dataset = lending_co_data_numerich


In [164]:
lending_co_data_numerich_intger=lending_co_data_numerich.astype(dtype = np.int32)
lending_co_data_numerich_intger
## this output data have dtype as intger32

array([[ 2000,    40,   365,  3121,  4241, 13621],
       [ 2000,    40,   365,  3061,  4171, 15041],
       [ 1000,    40,   365,  2160,  3280, 15340],
       ...,
       [ 2000,    40,   365,  4201,  5001, 16600],
       [ 1000,    40,   365,  2080,  3320, 15600],
       [ 2000,    40,   365,  4601,  4601, 16600]], dtype=int32)

In [163]:
lending_co_data_numerich_string = lending_co_data_numerich.astype(dtype = np.str_)
lending_co_data_numerich_string
## this output data have dtype as string (str)

array([['2000.0', '40.0', '365.0', '3121.0', '4241.0', '13621.0'],
       ['2000.0', '40.0', '365.0', '3061.0', '4171.0', '15041.0'],
       ['1000.0', '40.0', '365.0', '2160.0', '3280.0', '15340.0'],
       ...,
       ['2000.0', '40.0', '365.0', '4201.0', '5001.0', '16600.0'],
       ['1000.0', '40.0', '365.0', '2080.0', '3320.0', '15600.0'],
       ['2000.0', '40.0', '365.0', '4601.0', '4601.0', '16600.0']],
      dtype='<U32')

In [167]:
type(lending_co_data_numerich)

numpy.ndarray

#### casting doesnot affected directly the current dataset , so store it


In [168]:
## casting doesnot affected directly the current dataset , so store it
lending_co_data_numerich

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

## __NB:__ You cannot convert directly __String__ dataset to __Integer__
#### So do casting from __String__ to __Float__ and from __Float__ to __Intiger__

In [169]:
lending_co_data_numerich_float = lending_co_data_numerich_string.astype(dtype = np.float32)
lending_co_data_numerich_float

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], dtype=float32)

In [170]:
lending_co_data_numerich_int = lending_co_data_numerich_float.astype(dtype =np.int32)
lending_co_data_numerich_int

array([[ 2000,    40,   365,  3121,  4241, 13621],
       [ 2000,    40,   365,  3061,  4171, 15041],
       [ 1000,    40,   365,  2160,  3280, 15340],
       ...,
       [ 2000,    40,   365,  4201,  5001, 16600],
       [ 1000,    40,   365,  2080,  3320, 15600],
       [ 2000,    40,   365,  4601,  4601, 16600]], dtype=int32)

## Another way to solve same problem of __Casting__

In [172]:
## Let's import again the intire dataset.
lending_co_data_numericl = np.loadtxt('Lending-company-Numeric.csv',delimiter=',')
lending_co_data_numericl_str = lending_co_data_numericl.astype(dtype =np.str_)
lending_co_data_numericl_str

array([['2000.0', '40.0', '365.0', '3121.0', '4241.0', '13621.0'],
       ['2000.0', '40.0', '365.0', '3061.0', '4171.0', '15041.0'],
       ['1000.0', '40.0', '365.0', '2160.0', '3280.0', '15340.0'],
       ...,
       ['2000.0', '40.0', '365.0', '4201.0', '5001.0', '16600.0'],
       ['1000.0', '40.0', '365.0', '2080.0', '3320.0', '15600.0'],
       ['2000.0', '40.0', '365.0', '4601.0', '4601.0', '16600.0']],
      dtype='<U32')

In [173]:
lending_co_d_integer = lending_co_data_numericl_str.astype(dtype=np.float32).astype(dtype=np.int32)
lending_co_d_integer

## By repeating the same process

array([[ 2000,    40,   365,  3121,  4241, 13621],
       [ 2000,    40,   365,  3061,  4171, 15041],
       [ 1000,    40,   365,  2160,  3280, 15340],
       ...,
       [ 2000,    40,   365,  4201,  5001, 16600],
       [ 1000,    40,   365,  2080,  3320, 15600],
       [ 2000,    40,   365,  4601,  4601, 16600]], dtype=int32)

## Stripping Values

### Importing and specifying the number of column is needed for the model buliding.

In [208]:
## importing the data
# We only want the coluns which contain non-numeric data

lending_co_total_price = np.genfromtxt('Lending-Company-Total-Price.csv',
                                   delimiter=',', skip_header=1,
                                   dtype = np.str_,
                                   usecols=[1,2,4])
lending_co_total_price

array([['id_1', 'Product B', 'Location 2'],
       ['id_2', 'Product B', 'Location 3'],
       ['id_3', 'Product C', 'Location 5'],
       ...,
       ['id_413', 'Product B', 'Location 135'],
       ['id_414', 'Product C', 'Location 200'],
       ['id_415', 'Product A', 'Location 8']], dtype='<U12')

#### __Stripping__
#### means Removing a specific parts of the string

#### Not straight up deleting the values store in specific positions...
#### But rather taking away small parts

##### Using method __chararray.strip()__

In [211]:
## Let's delete 'id_' from the first column of the dataset

lending_co_total_price1=  np.chararray.strip(lending_co_total_price[:,0],"id_")

## we stored the result in lending_co_total_price1 bcz stripping doesnot 
## modify the array

In [225]:
lending_co_total_price1

chararray(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
           '13', '14', '15', '16', '17', '18', '19', '20', '21', '22',
           '23', '24', '25', '26', '27', '28', '29', '30', '31', '32',
           '33', '34', '35', '36', '37', '38', '39', '40', '41', '42',
           '43', '44', '45', '46', '47', '48', '49', '50', '51', '52',
           '53', '54', '55', '56', '57', '58', '59', '60', '61', '62',
           '63', '64', '65', '66', '67', '68', '69', '70', '71', '72',
           '73', '74', '75', '76', '77', '78', '79', '80', '81', '82',
           '83', '84', '85', '86', '87', '88', '89', '90', '91', '92',
           '93', '94', '95', '96', '97', '98', '99', '100', '101', '102',
           '103', '104', '105', '106', '107', '108', '109', '110', '111',
           '112', '113', '114', '115', '116', '117', '118', '119', '120',
           '121', '122', '123', '124', '125', '126', '127', '128', '129',
           '130', '131', '132', '133', '134', '135', '136', '1

In [232]:
lending_co_total_price2 =  np.chararray.strip(lending_co_total_price[:,1],"Product ")
lending_co_total_price2
## remove alsoe the empty space

chararray(['B', 'B', 'C', 'B', 'D', 'B', 'A', 'B', 'A', 'A', 'B', 'D',
           'B', 'A', 'A', 'B', 'A', 'B', 'B', 'E', 'B', 'A', 'A', 'C',
           'D', 'A', 'A', 'F', 'D', 'B', 'B', 'B', 'A', 'B', 'A', 'B',
           'B', 'B', 'C', 'B', 'B', 'B', 'A', 'C', 'A', 'B', 'B', 'B',
           'D', 'A', 'B', 'A', 'D', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
           'A', 'C', 'C', 'D', 'B', 'A', 'A', 'D', 'A', 'B', 'C', 'B',
           'B', 'A', 'A', 'A', 'A', 'D', 'D', 'D', 'A', 'B', 'A', 'D',
           'B', 'A', 'A', 'B', 'A', 'B', 'A', 'D', 'B', 'B', 'A', 'B',
           'B', 'A', 'A', 'B', 'B', 'A', 'B', 'A', 'A', 'B', 'B', 'A',
           'B', 'A', 'B', 'C', 'B', 'D', 'B', 'A', 'A', 'A', 'C', 'A',
           'A', 'B', 'D', 'B', 'B', 'A', 'A', 'B', 'B', 'B', 'C', 'B',
           'C', 'A', 'D', 'B', 'D', 'A', 'C', 'B', 'B', 'B', 'C', 'B',
           'C', 'A', 'A', 'A', 'A', 'A', 'B', 'A', 'E', 'E', 'B', 'A',
           'A', 'A', 'A', 'C', 'A', 'B', 'A', 'D', 'A', 'B', 'A', 'A',
      

In [255]:
#Array =[]
#for x in lending_co_total_price2:
   # if x == 'A':
        #Array.append(x)

In [257]:
len(Array)

163

In [258]:
#Array2 =[]
#for x in lending_co_total_price2:
    #if x == 'B':
       # Array2.append(x)
#len(Array2)        

166

In [259]:
#Array3 =[]
#for x in lending_co_total_price2:
   # if x == 'C':
       # Array3.append(x)
#len(Array3)  

39

In [262]:
lending_co_total_price3 =  np.chararray.strip(lending_co_total_price[:,2],"Location ")
#lending_co_total_price3
## remove alsoe the empty space

## stripping of the 3 columns

In [267]:
lending_co_total_price[:,0]=  np.chararray.strip(lending_co_total_price[:,0],"id_")
lending_co_total_price[:,1] =  np.chararray.strip(lending_co_total_price[:,1],"Product ")
lending_co_total_price[:,2] =  np.chararray.strip(lending_co_total_price[:,2],"Location ")
lending_co_total_price

## stripping done

array([['1', 'B', '2'],
       ['2', 'B', '3'],
       ['3', 'C', '5'],
       ...,
       ['413', 'B', '135'],
       ['414', 'C', '200'],
       ['415', 'A', '8']], dtype='<U12')

### Let's transform the  dataset into numeric now 

## using __np.where()__ method

### NB: only the 2nd column is not numeric, let's transform it.

In [268]:
lending_co_total_price[:,1] = np.where(lending_co_total_price[:,1]== 'A',1,lending_co_total_price[:,1])
lending_co_total_price[:,1] = np.where(lending_co_total_price[:,1]== 'B',2,lending_co_total_price[:,1])
lending_co_total_price[:,1] = np.where(lending_co_total_price[:,1]== 'C',3,lending_co_total_price[:,1])
lending_co_total_price[:,1] = np.where(lending_co_total_price[:,1]== 'D',4,lending_co_total_price[:,1])
lending_co_total_price[:,1] = np.where(lending_co_total_price[:,1]== 'E',5,lending_co_total_price[:,1])
lending_co_total_price[:,1] = np.where(lending_co_total_price[:,1]== 'F',6,lending_co_total_price[:,1])

In [269]:
lending_co_total_price

array([['1', '2', '2'],
       ['2', '2', '3'],
       ['3', '3', '5'],
       ...,
       ['413', '2', '135'],
       ['414', '3', '200'],
       ['415', '1', '8']], dtype='<U12')

## Let's Remove the quotetion around each number is the array ('')

In [270]:
lending_co_total_price = lending_co_total_price.astype(dtype = np.int32)
lending_co_total_price

array([[  1,   2,   2],
       [  2,   2,   3],
       [  3,   3,   5],
       ...,
       [413,   2, 135],
       [414,   3, 200],
       [415,   1,   8]], dtype=int32)

## Explore __Stacking__

#### __np.stack__ , __np.vstack__ , __np.hstack__ , __np.dstack__

In [ ]:
#ls

In [273]:
lending_co_data_numeric = np.loadtxt('Lending-company-Numeric.csv',delimiter=',')
#lending_co_data_numeric

In [294]:
lending_co_data_numeric_NAN = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter=';')

temporary_fill = np.nanmax(lending_co_data_numeric_NAN).round(2) + 1




In [295]:
tempory_mean = np.nanmean(lending_co_data_numeric_NAN, axis=0).round(2)

In [296]:
lending_co_data_numeric_NAN = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',
                                            delimiter=';',
                                            filling_values = temporary_fill)



In [297]:
length = lending_co_data_numeric_NAN.shape[1]



(1043, 6)

In [299]:
for x in range(lending_co_data_numeric_NAN.shape[1]):
    lending_co_data_numeric_NAN [:,x] = np.where(lending_co_data_numeric_NAN[:,x] == temporary_fill,
                                                temporary_mean[x],
                                                lending_co_data_numeric_NAN[:,x])
lending_co_data_numeric_NAN 

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2250.25,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]])

### __Stacking:__

### It's placing multiple objects on top of one another to create a bigger(larger) Object

#### We can just __arrays__ of matching shapes to create a larger array = a "Stack"

In [307]:
## example with first dataset lending_co_data_numeric

np.stack((lending_co_data_numeric[:,0],lending_co_data_numeric[:,1]))

array([[2000., 2000., 1000., ..., 2000., 1000., 2000.],
       [  40.,   40.,   40., ...,   40.,   40.,   40.]])

In [308]:
## changing of row

np.stack((lending_co_data_numeric[:,1],lending_co_data_numeric[:,0]))

array([[  40.,   40.,   40., ...,   40.,   40.,   40.],
       [2000., 2000., 1000., ..., 2000., 1000., 2000.]])

In [309]:
array1 = np.stack((lending_co_data_numeric[:,1],lending_co_data_numeric[:,0]))

In [310]:
## 

np.transpose(array1)

array([[  40., 2000.],
       [  40., 2000.],
       [  40., 1000.],
       ...,
       [  40., 2000.],
       [  40., 1000.],
       [  40., 2000.]])

In [311]:
## without np.transpose we can set axis = 1 and get same result

np.stack((lending_co_data_numeric[:,0],lending_co_data_numeric[:,1]),axis=1)

array([[2000.,   40.],
       [2000.,   40.],
       [1000.,   40.],
       ...,
       [2000.,   40.],
       [1000.,   40.],
       [2000.,   40.]])

In [313]:
## let's one more clumn of dataset

np.stack((lending_co_data_numeric[:,0],lending_co_data_numeric[:,1],lending_co_data_numeric[:,2]),axis=1)


array([[2000.,   40.,  365.],
       [2000.,   40.,  365.],
       [1000.,   40.,  365.],
       ...,
       [2000.,   40.,  365.],
       [1000.,   40.,  365.],
       [2000.,   40.,  365.]])

## __np.vstack()__

In [314]:
## first let's check the shape of the both arrays

lending_co_data_numeric.shape

(1043, 6)

In [315]:
lending_co_data_numeric_NAN.shape

(1043, 6)

#### The above both arrays have the same shape , cool

In [316]:
vertical_stack = np.vstack((lending_co_data_numeric,lending_co_data_numeric_NAN))

In [319]:
vertical_stack

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2250.25,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]])

In [317]:
### let's check it using the shape method

vertical_stack.shape

(2086, 6)

## __np.hstack()__

In [321]:
horizontal_stack = np.hstack((lending_co_data_numeric,lending_co_data_numeric_NAN))
horizontal_stack

array([[ 2000.,    40.,   365., ...,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365., ...,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365., ...,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365., ...,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365., ...,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365., ...,  4601.,  4601., 16600.]])

In [322]:
# let's check it using the shape method
horizontal_stack.shape

(1043, 12)

 ## __np.dstack__
#### d stack = depth satck
#### We satck the arrays in the third dimension
#### Returns an arrays of a hight dimension    


In [323]:
depth_stack = np.dstack((lending_co_data_numeric,lending_co_data_numeric_NAN))
depth_stack

array([[[ 2000.  ,  2000.  ],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 3121.  ,  3121.  ],
        [ 4241.  ,  4241.  ],
        [13621.  , 13621.  ]],

       [[ 2000.  ,  2000.  ],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 3061.  ,  3061.  ],
        [ 4171.  ,  4171.  ],
        [15041.  , 15041.  ]],

       [[ 1000.  ,  1000.  ],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 2160.  ,  2160.  ],
        [ 3280.  ,  3280.  ],
        [15340.  , 15340.  ]],

       ...,

       [[ 2000.  ,  2250.25],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 4201.  ,  4201.  ],
        [ 5001.  ,  5001.  ],
        [16600.  , 16600.  ]],

       [[ 1000.  ,  1000.  ],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 2080.  ,  2080.  ],
        [ 3320.  ,  3320.  ],
        [15600.  , 15600.  ]],

       [[ 2000.  ,  2000.  ],
        [   40.  ,    40.  ],
        [  365.  

In [326]:
depth_stack[0]

array([[ 2000.,  2000.],
       [   40.,    40.],
       [  365.,   365.],
       [ 3121.,  3121.],
       [ 4241.,  4241.],
       [13621., 13621.]])

In [327]:
len(depth_stack)

1043

In [329]:
#for x in depth_stack:
#    print(x)

In [330]:
# let's check it using the shape method
depth_stack.shape

(1043, 6, 2)

In [333]:
depth_stack[0,:,0]

array([ 2000.,    40.,   365.,  3121.,  4241., 13621.])

# __Concatinating__

#### Linking together objects in a chain
#### Creating a new (larger) array by merging existing smaller arrays along a given axis
#### The inputs and the outputs of the __np.concatenate()__ function always have the same number of dimensions.

In [334]:
## let's import the dataset

lending_co_data_numeric = np.loadtxt('Lending-company-Numeric.csv',delimiter=',')

lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [335]:
lending_co_data_numeric[0,:]

array([ 2000.,    40.,   365.,  3121.,  4241., 13621.])

In [336]:
concat = np.concatenate((lending_co_data_numeric[0,:],lending_co_data_numeric[0,:]))

In [339]:
## the result here is one dimension as the 1st row and the 2nd row
concat

array([ 2000.,    40.,   365.,  3121.,  4241., 13621.,  2000.,    40.,
         365.,  3121.,  4241., 13621.])

In [338]:
len(concat)

12

### let's concatinate 2D arrays

In [340]:
lending_co_data_numeric_NAN = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',delimiter=';')

temporary_fill = np.nanmax(lending_co_data_numeric_NAN).round(2) + 1
tempory_mean = np.nanmean(lending_co_data_numeric_NAN, axis=0).round(2)

lending_co_data_numeric_NAN = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv',
                                            delimiter=';',
                                            filling_values = temporary_fill)

for x in range(lending_co_data_numeric_NAN.shape[1]):
    lending_co_data_numeric_NAN [:,x] = np.where(lending_co_data_numeric_NAN[:,x] == temporary_fill,
                                                temporary_mean[x],
                                                lending_co_data_numeric_NAN[:,x])
lending_co_data_numeric_NAN




array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2250.25,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]])

In [342]:
both_arrays = np.concatenate((lending_co_data_numeric,lending_co_data_numeric_NAN))
both_arrays

## the Ouput is a 2D arrays and larger

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2250.25,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]])

In [343]:
len(both_arrays)

2086

In [344]:
both_arrays.shape

(2086, 6)

### let's set axis = 1 , for horizontal concatination


### the input arrays are 2D , we can set  axis = 1

### for 3D , we can set axis = 2

In [345]:
### let's set axis = 1 , for horizontal concatination

both_arrays1 = np.concatenate((lending_co_data_numeric,lending_co_data_numeric_NAN),axis =1)
both_arrays1

## the input arrays are 2D , we can axis = 1

## for 3D , we can set axis =2

array([[ 2000.,    40.,   365., ...,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365., ...,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365., ...,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365., ...,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365., ...,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365., ...,  4601.,  4601., 16600.]])

In [346]:
both_arrays1.shape

(1043, 12)

# __Unique__ in the __data__

In [347]:
## let's import the dataset

lending_co_data_numeric = np.loadtxt('Lending-company-Numeric.csv',delimiter=',')

lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

### __np.unique__

In [348]:
np.unique(lending_co_data_numeric)

array([-2870., -2550., -2450., ..., 52751., 54625., 64001.])

In [350]:
## Unique values in the 2nd column

np.unique(lending_co_data_numeric[:,1])

array([ 35.,  40.,  50., 125., 165.])

In [351]:
## Unique values in the 2nd row


np.unique(lending_co_data_numeric[1])

array([   40.,   365.,  2000.,  3061.,  4171., 15041.])

## Unique values in the 2nd column and __count__ per each element


In [352]:
## Unique values in the 2nd column and count per each element

np.unique(lending_co_data_numeric[:,1], return_counts=True)

(array([ 35.,  40.,  50., 125., 165.]), array([  4, 567, 451,  19,   2]))

## Unique values in the 2nd column and count per each element
### set return_index = True 


In [354]:
## Unique values in the 2nd column and count per each element
### set return_index = True 

avk = np.unique(lending_co_data_numeric[:,1], return_counts=True,return_index = True)

In [355]:
avk

(array([ 35.,  40.,  50., 125., 165.]),
 array([327,   0,   4,  19,  27]),
 array([  4, 567, 451,  19,   2]))